config/routes.rb
Rails.application.routes.draw do




  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/home/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    get "/customers/:id/unsubscribe" => "customers#unsubscribe", as: 'customers/unsubscribe'
    patch "/customers/:id/withdraw" => "customers#withdraw", as: 'customers/withdraw'
    resources :customers, only: [:show, :edit, :update]
    
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    post 'orders/confirm' => "orders#confirm"
    get 'orders/complete' => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  
  
  def subtotal
    item.add_tax_price * amount
  end
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def full_name
    self.last_name + " " + self.first_name
  end     
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
         
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :orders, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  has_one_attached :image
  
  
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_yoko.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  
  def add_tax_price
    (price * 1.08).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: {
     "入金待ち":0, 
     "入金確認":1, 
     "製作中":2, 
     "発送準備中":3, 
     "発送済み":4
  }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
     "製作不可":0,
     "製作待ち":1,
     "製作中":2,
     "製作完了":3,
  }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
		@customer.update(customer_params)
		redirect_to admin_customer_path
  end

  private

  def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:adress,:telephone_number,:email,:is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    @genre.save
    render :index
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    
    redirect_to admin_order_path
  end

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if customer_signed_in?
        root_path#login後遷移path要変更確認用なので
    else
      admin_root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else root_path
    end
  end

  protected



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                           :last_name,
                                                           :kana_first_name,
                                                           :kana_last_name,
                                                           :email,
                                                           :postal_code,
                                                           :address,
                                                           :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <h2><%= @customer.full_name %>さんの会員情報編集</h2>

  <%= form_with model: @customer, url:admin_customer_path do |f| %>

    <%= f.label :"会員" %>
      <%= f.label :"#{@customer.id}" %>
    <%= f.label :"氏名" %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
    <%= f.label :"フリガナ" %>
      <%= f.text_field :kana_first_name %>
      <%= f.text_field :kana_last_name %>
    <%= f.label :"郵便番号" %>
      <%= f.text_field :post_code %>
    <%= f.label :"電話番号" %>
      <%= f.text_field :telephone_number %>
    <%= f.label :"メールアドレス" %>
      <%= f.text_field :email %>

    <%= f.label :"会員ステータス" %>
      <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '退会', value: true %>
      <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '有効', value: false %>

    <%= f.submit "変更を保存" %>

  <% end %>

</main>

app/views/admin/customers/index.html.erb
<nain>
  <h2>会員一覧</h2>

  <table>
    <thead>
      <tr>
        <th>会員id</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to (customer.last_name + customer.first_name),admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted %>
              <%= "退会" %>
            <% else %>
              <%= "有効" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</nain>

app/views/admin/customers/show.html.erb
<main>
  <h2><%= @customer.full_name %>さんの会員詳細</h2>

  <table>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>フリガナ</th>
        <th>郵便番号</th>
        <th>住所</th>
        <th>電話番号</th>
        <th>メールアドレス</th>
        <th>会員ステータス</th>
      </tr>
      <tbody>
        <tr>
          <td><%= @customer.id %></td>
          <td><%= (@customer.first_name + @customer.last_name) %></td>
          <td><%= (@customer.kana_first_name + @customer.kana_last_name) %></td>
          <td><%= @customer.postal_code.to_s.insert(3, "-") %></td>
          <td><%= @customer.address %></td>
          <td><%= @customer.telephone_number %></td>
          <td><%= @customer.email %></td>
          <td>
            <% if @customer.is_deleted %>
              <%= "退会" %>
            <% else %>
              <%= "有効" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </thead>
  </table>

  <%= link_to "編集する",edit_admin_customer_path(@customer) %>
  <%= link_to "注文履歴を見る", admin_root_path %>

</main>