config/routes.rb
Rails.application.routes.draw do




  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/home/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    get "/customers/:id/unsubscribe" => "customers#unsubscribe", as: 'customers/unsubscribe'
    patch "/customers/:id/withdraw" => "customers#withdraw", as: 'customers/withdraw'
    resources :customers, only: [:show, :edit, :update]
    
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    post 'orders/confirm' => "orders#confirm"
    get 'orders/complete' => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  
  
  def subtotal
    item.add_tax_price * amount
  end
  
  belongs_to :customer
  belongs_to :item
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def full_name
    self.last_name + " " + self.first_name
  end     
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
         
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :orders, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  has_one_attached :image
  
  
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_yoko.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  
  def add_tax_price
    (price * 1.08).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: {
     "入金待ち":0, 
     "入金確認":1, 
     "製作中":2, 
     "発送準備中":3, 
     "発送済み":4
  }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
     "製作不可":0,
     "製作待ち":1,
     "製作中":2,
     "製作完了":3,
  }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    @genre.save
    render :index
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    
    redirect_to admin_order_path
  end

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if customer_signed_in?
        root_path#login後遷移path要変更確認用なので
    else
      admin_root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else root_path
    end
  end

  protected



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                           :last_name,
                                                           :kana_first_name,
                                                           :kana_last_name,
                                                           :email,
                                                           :postal_code,
                                                           :address,
                                                           :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mr-6">
      <h2 class="bg-light mt-4 mb-4 col-9">ジャンル編集</h2>
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <%= f.label :"ジャンル名" %>
        <%= f.text_field :name %>
        <%= f.submit "変更を保存" , class: "ml-3 btn btn-primary genre_btn" %>
      <% end %> 
      </div>
    </div>
  </div>
</main>

app/views/admin/genres/index.html.erb
<main>
  <div class="container">
  <div class="row">
    <div class="col-md-6">
<h2 class="bg-light mt-3 col-8">ジャンル一覧・追加</h2>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <h4 class="mt-4">ジャンル名</h4>
    <%= f.text_field :name %>
  <%= f.submit '新規登録', class: "btn btn-primary genre_btn ml-3" %>
<% end %>
<h4 class="bg-light mt-4">ジャンル</h4>
<table class='table genre-table'>
  <% @genres.each do |genre| %>
  <tbody class="genre_area">
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-primary genre_btn" %></td>
    </tr>
  </tbody>
  <% end %>
</table>

</div>
</div>
</div>

</main>

app/views/admin/homes/top.html.erb
<main>
  <div class="container">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-9">
  <h3>注文履歴一覧</h3>

  <table class='table order-table'>
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <th><%=link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></th>
        <th><%= order.customer.first_name %><%= order.customer.last_name %></th>
        <th>
          <%= order.order_details.sum(:amount) %>
        </th>
        <th><%= order.status %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
   </div>
    <div class="col-xs-2"></div>
  </div>

</main>

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    
  <h3 class="mt-3">商品編集</h3>
  <div class="row">
  <%= form_with model: @item, url:admin_item_path do |f| %>
    <div class="form-group">
    <%= f.label :商品画像 %>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
    <%= f.label :商品名 %>
      <%= f.text_field :name, size:"45x5" %>
    </div>
    <div class="form-group">
      <div class="align-top">
    <%= f.label :商品説明 %>
      </div>
      <%= f.text_area :introduction, size:"55x5" %>
    </div>
    <div class="form-group">
    <%= f.label :ジャンル %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "--選択してください--"} %>
    </div>
    <div class="form-group">
    <%= f.label :税抜価格 %>
      <%= f.text_field :price %>
    </div>
    <div class="form-group">
    <%= f.label :販売ステータス %>
      <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中', value: false %>
    </div>
    <div>
    <%= f.submit "変更を保存" %>
    </div>
  <% end %>
  </div>
</div>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
  <div class="row">
  <h4 class="mt-3">商品一覧</h4>
  <div class="col-xs-9 mt-3">
    <div class="text-right">
      <%= link_to new_admin_item_path do %>
        <button type="button" class="btn-outline-dark rounded-circle btn-md">＋</button>
      <% end %>
    </div>
  <table class="table item-table mt-3">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item) %></td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <td>
          <% if item.is_active %>
            <%= "販売中" %>
          <% else %>
            <%=  "販売停止中" %>
          <% end %>
        </td>
      </tr>
      <% end %>
      
      
    </tbody>
  </table>
  <%= paginate @items %>
</div>
</div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-12">
  <h4 class="bg-light col-6 mt-3 ml-5">商品新規登録</h4>


  <%= form_with model: @item,url:admin_items_path do |f| %>
    <div class="mx-auto" style="width: 700px;">
    <div class="mt-3 mb-3">
    <%= f.label :商品画像 %>
      <%= f.file_field :image %>
    </div>


    <div class="form-group">
    <%= f.label :商品名, class:"col-xs-2" %>
      <%= f.text_field :name, size:"50x5" %>
    </div>
    <div class="form-group">
      <div class="align-top">
    <%= f.label :商品説明, class:"col-xs-2" %>
      </div>
      <%= f.text_area :introduction, size:"60x10" %>
    </div>

     <div class="form-group">
    <%= f.label :ジャンル, class:"col-xs-2" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "--選択してください--"} %>
    </div>

    <div class="form-group">
    <%= f.label :税抜価格, class:"col-xs-2" %>
      <%= f.text_field :price %>円
    </div>

    <div class="form-group">
    <%= f.label :販売ステータス %>
      <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中', value: false %>
    </div>

    <%= f.submit "新規登録", class: "btn btn-primary pull-right" %>
    </div>
  <% end %>


  <div class="col-xs-2"></div>
  </div>
  </div>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">

      <div>
        <h3 class="bg-light mt-3">商品詳細</h3>
      </div>
  <div class="row">
  <div class="col-5">
    <%= image_tag @item.get_image(300,250) %>
  </div>
    <div class="col-7">
      <div>
        <p class="mt-3"><strong>商品名：</strong><%= @item.name %></p>
      </div>
      <br>
      <div>
        <p><strong>商品説明：</strong><%= @item.introduction %></p>
      </div>
      <br>
      <div>
        <p><strong>ジャンル：</strong><%= @item.genre.name %></p>
      </div>
      <br>
      <div><strong><p>税込価格(税抜価格)：</strong>
          <%= @item.price.to_s(:delimited) %>
          (<%= @item.add_tax_price.to_s(:delimited) %>) 円
          </p>
      </div>
      <br>
      <div><p><strong>販売ステータス：</strong>
        <% if @item.is_active == true %>
          <%= "販売中" %>
        <% else %>
          <%= "販売停止中" %>
        <% end %>
        </p>
      </div>
      <div>
      <%= link_to "編集する",edit_admin_item_path(@item), class:"btn btn-primary" %>
      </div>
      </div>
    </div>
  </div>
</main>

app/views/admin/orders/show.html.erb
<main>
  <h3>注文履歴詳細</h3>

  <table class="table">
    <tbody>
      <tr>
        <th scope="row">購入者</th>
        <%= link_to admin_customer_path(@order) do %>
          <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
      </tr>
      <tr>
        <th scope="row">配送先</th>
        <td>
          <p><%= @order.postal_code %><%= @order.address %></p>
          <p><%= @order.name %></p>
        </td>
      </tr>
      <tr>
        <th scope="row">支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th scope="row">注文ステータス</th>
        <td>
          <%= form_with model:@order, url: admin_order_path do |f| %>
            <%= f.select :status, Order.statuses.keys %>
            <%= f.submit "更新", class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-8"style="margin-top: 50px;">
    <table class="table table-bordered">
      <thead>
        <tr class="table-head" style="background-color:#F5F5F5;">
          <th scope="col">商品名</th>
          <th scope="col">単価（税込）</th>
          <th scope="col">数量</th>
          <th scope="col">小計</th>
          <th scope="col">製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td>¥<%= (order_detail.price*1.1).floor.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td>¥<%= ((order_detail.price * order_detail.amount*1.1).floor).to_s(:delimited) %></td>
            <td>
              <%= form_with model:order_detail, url: admin_order_detail_path(order_detail) do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys %>
                <%= f.submit "更新", class: 'btn btn-primary' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xs-4">
    <div>
      <p>
        <strong class="col-xs-3">商品合計</strong>
         ¥<%= (@order.total_payment).to_s(:delimited)%>
      </p>
    </div>
    <br>
    <div>
      <p>
        <strong class="col-xs-2">送料</strong>
        ¥<%= @order.shipping_cost %>
      </p>
    </div>
    <br>

    <div>
      <p>
        <strong class="col-xs-4">請求金額合計</strong>
        ¥<%= @order.total_payment.to_s(:delimited) %>
      </p>
    </div>
    <br>
  </div>
</div>

</div>
</main>